# Generated by Django 3.2 on 2022-02-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Contrasenia')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default=1, max_length=20)),
                ('categoriaName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categoria', verbose_name='Categoria Name')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
