# Generated by Django 3.2 on 2022-02-16 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha de registro'),
        ),
    ]
