# Generated by Django 3.2 on 2022-02-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_producto_date_joined'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='usuarios',
        ),
    ]
