# Generated by Django 3.2.9 on 2022-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220111_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioCompra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio Venta'),
        ),
    ]
