# Generated by Django 3.2.9 on 2022-01-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220111_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
        ),
    ]
