# Generated by Django 3.2.9 on 2022-01-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0005_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoriaName',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='category.categoria', verbose_name='Categoria Name'),
            preserve_default=False,
        ),
    ]
