# Generated by Django 3.2 on 2022-02-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producto_categorianame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precioCompra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precioVenta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='apellido',
            field=models.CharField(default=1, max_length=30, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='direccion',
            field=models.CharField(default=1, max_length=30, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='email',
            field=models.CharField(default=1, max_length=30, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='password',
            field=models.CharField(default=2, max_length=30, verbose_name='Contrasenia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
