# Generated by Django 3.2 on 2022-02-07 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220207_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='date_join',
            field=models.DateTimeField(default=2, verbose_name=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
