# Generated by Django 3.2 on 2022-02-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_producto_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='email',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
