# Generated by Django 3.2 on 2022-02-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_producto_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='date_join',
            field=models.DateTimeField(),
        ),
    ]
