# Generated by Django 3.2 on 2022-02-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas',
            name='paginas',
            field=models.CharField(max_length=50, verbose_name='Ingrese pagina a visitar'),
        ),
    ]
